name: "flutterwave"
description: "Flutterwave official flutter library to accept payment via card, USSD, Mobile Money etc."
version: 0.0.3-dev.3
homepage: "https://github.com/Flutterwave/flutterwave-flutter"
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.1.0
  flutter_spinkit: ^5.0.0
  intl_phone_number_input: ^0.7.0+2
  credit_card_validator: ^2.0.0



  http: ^0.13.3
  tripledes:
    git:
      url: https://github.com/wilburt/tripledes-dart.git
      ref: null-safety
  webview_flutter: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.0.10


flutter_icons:
  ios: true
  android: true

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/mpesa.png

  fonts:
    - family: FLW
      fonts:
        - asset: fonts/FLW-Regular.ttf
        - asset: fonts/FLW-Bold.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Black.ttf
        - asset: fonts/Poppins-BlackItalic.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-BoldItalic.ttf
        - asset: fonts/Poppins-ExtraBold.ttf
        - asset: fonts/Poppins-ExtraBoldItalic.ttf
        - asset: fonts/Poppins-ExtraLight.ttf
        - asset: fonts/Poppins-ExtraLightItalic.ttf
        - asset: fonts/Poppins-Italic.ttf
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-LightItalic.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-MediumItalic.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-SemiBoldItalic.ttf
        - asset: fonts/Poppins-Thin.ttf
        - asset: fonts/Poppins-ThinItalic.ttf

